### ISSUE TITLE
Problems reading /diagnostic messages

### ISSUE THREAD

**Issue by rzlot** [bcharrow/matlab_rosbag#1]
There seems to be some problematic syntax in the DiagnosticsStatus struct (http://ros.org/doc/api/diagnostic_msgs/html/msg/DiagnosticStatus.html) that causes an exception to be thrown when parsing the message definition. The message definition includes essentially an enumerated type for the 'level' field.
Here is the error message:

``` matlab
>> msgs = bag.readAllMessages('/diagnostics');
Unexpected Standard exception from MEX file.
What() is:Bad field 'OK=0':
MSG: diagnostic_msgs/DiagnosticStatus
# This message holds the status of an individual component of the robot.
#

# Possible levels of operations
byte OK=0
byte WARN=1
byte ERROR=2

byte level # level of operation enumerated above
string name # a description of the test/component reporting
string message # a description of the status
string hardware_id # a hardware unique string
KeyValue[] values # an array of values associated with the status


Error in ros.Bag/readAllMessages (line 64)
                msg = rosbag_wrapper(obj.handle, 'readAllMessages', false);
```

**Comment by bcharrow** [comment]
Thanks for the full exception.  The parsing code doesn't currently support constants.  I'll fix this soon, but it will be at least a week.

**Comment by bcharrow** [comment]
The issue should now be fixed. Can you please confirm with one of these links:

http://www.seas.upenn.edu/~bcharrow/media/code/matlab_rosbag-0.1.2-mac64.zip
http://www.seas.upenn.edu/~bcharrow/media/code/matlab_rosbag-0.1.2-linux64.zip

**Comment by rzlot** [comment]
I have tested it on both my Linux and OS X installs, and it works with diagnostics messages now.
Much appreciated! Thanks!
