### ISSUE TITLE
Problem with std_msgs/Empty

### ISSUE THREAD

**Issue by flaviofontana** [bcharrow/matlab_rosbag#10]
Hi there 

I found a problem opening bags in Matlab which contain std_msgs/Empty
I always get the Error  

Unexpected Standard exception from MEX file.
What() is:vector::_M_range_check
..

Error in ros.Bag (line 30)
            obj.handle = rosbag_wrapper(uint64(0), 'construct', 'ROSBagWrapper', obj.path);

Cheers,
flavio

**Comment by bcharrow** [comment]
Thanks for the report, Flavio!  I think I've fixed the issue.  Can you please confirm the fix by downloading v0.4.1 from the release page and running it on the bag you were using?
https://github.com/bcharrow/matlab_rosbag/releases/download/v0.4/matlab_rosbag-0.4.1-linux64.zip

**Comment by cinatale** [comment]
Could it be possible to have the compiled version for Linux32 also?

Thanks,
C.

**Comment by bcharrow** [comment]
Unfortunately, I don't have easy access to a 32 bit machine.  I haven't posted the 32 bit version you sent yet, because I haven't had a chance to verify it.
