### ISSUE TITLE
write bag file in matlab? reopen?

### ISSUE THREAD

**Issue by talregev** [bcharrow/matlab_rosbag#12]
Here a java project that start write bag file.
Can it improve it, and combine it with your work?
and eventually write a bag file inside matlab?

[ROS Wiki](http://www.ros.org/news/2014/11/a-rosbag-implementation-in-java.html)
[Github](https://bitbucket.org/aaron_sims/jrosbag/src)

Regards,
Tal

**Comment by bcharrow** [comment]
Being able to write a bag file in matlab would be great, but unfortunately I don't have time to work on this.  Please let me know if this is something you would like to do, and we can discuss a good API and how to implement it.

**Comment by talregev** [comment]
I Look at your code, and understand it on c++, so java will not help in here.
Already implement ros bag record on c++.
So, if you have time, you can look on it.
[ROS Bag Record](https://github.com/ros/ros_comm/blob/indigo-devel/tools/rosbag/src/record.cpp)
[ROS Bag Wiki](http://wiki.ros.org/rosbag)
