### ISSUE TITLE
Tildes in filepaths not properly handled

### ISSUE THREAD

**Issue by rzlot** [bcharrow/matlab_rosbag#2]
When calling the Bag constructor, an exception is thrown if the path to the file contains a tilde:

``` matlab
>> bag = ros.Bag('~/tmp/bagfile_2012-12-19-17-40-50_0.bag');
Unexpected Standard exception from MEX file.
What() is:Error opening file: ~/tmp/bagfile_2012-12-19-17-40-50_0.bag


Error in ros.Bag (line 15)
            obj.handle = rosbag_wrapper(uint64(0), 'construct', bag);
```

The tilde can be expanded automatically into the full directory path using the standard C header wordexp.h as follows:

``` c++
#include <wordexp.h>
...
wordexp_t fname_exp; 
wordexp(fname.c_str(), &fname_exp, 0); // removes leading tilde if used for home dir
fname = fname_exp.we_wordv[0];          // overwrite the string, or create a new variable
wordfree(&fname_exp);
bag_.open(fname.c_str(), rosbag::bagmode::Read);
```

**Comment by bcharrow** [comment]
The issue should be fixed.  Can you please confirm with one of these links:

http://www.seas.upenn.edu/~bcharrow/media/code/matlab_rosbag-0.1.1-mac64.zip
http://www.seas.upenn.edu/~bcharrow/media/code/matlab_rosbag-0.1.1-linux64.zip

**Comment by rzlot** [comment]
Thanks for addressing this. I've tested it on both my Ubuntu and OS X installs and it appears to do the trick.
