### ISSUE TITLE
Instructions for libstdc++ Ubuntu problem

### ISSUE THREAD

**Issue by shomin** [bcharrow/matlab_rosbag#4]
On MATLAB2012a, Ubuntu 12.04, MATLAB looks in:

 /usr/local/MATLAB/bin/<systype>/ 

instead of 

 /usr/local/MATLAB/os/sys/<systype>/ 

for libstdc++ (although there are still some random libraries there).

The same fix still works of just getting them out of the path (by putting them in backup).

**Comment by bcharrow** [comment]
Thanks Mike!
