### ISSUE TITLE
matlab_rosbag in windows

### ISSUE THREAD

**Issue by ashfaqur-rahman** [bcharrow/matlab_rosbag#7]
Hi,

Is it possible for someone to create the mex32 files of the matlab_rosbag and upload that to sourceforge. I am unable to create the mexfiles for windows.

**Comment by bcharrow** [comment]
What problems are you encountering (e.g., compiler errors, link errors, etc.)  I don't have a windows machine, but am happy to help incorporate changes to get things working on windows.

**Comment by ashfaqur-rahman** [comment]
Following is the error that I got when I run mex

mex rosbag_wrapper.cpp
rosbag_wrapper.cpp 
rosbag_wrapper.cpp(6) : fatal error C1083: Cannot open include file: 'wordexp.h': No such file or directory 

  C:\PROGRA~1\MATLAB\R2013B\BIN\MEX.PL: Error: Compile of 'rosbag_wrapper.cpp' failed. 

Unable to complete successfully.

**Comment by bcharrow** [comment]
wordexp() provides posix shell style word expansion for paths (e.g., ~/directory -> /home/user/directory).  You can comment it out for now; if that's the only stumbling block I can change that logic so that it's cross platform.
