### ISSUE TITLE
Compiled versions

### ISSUE THREAD

**Issue by cinatale** [bcharrow/matlab_rosbag#9]
Hi! Is there a way to get a compiled version for windows x64?
As an alternative, a compiled version for Linux x32...

Thanks,
C.

**Comment by cinatale** [comment]
I have now a compiled version for linux 32bit. I can make it available if needed.
C.

**Comment by bcharrow** [comment]
Glad things worked out.  A version for windows x64 has been requested many times, but I don't have a windows machine.  If you end up making one, let me know and I'll make it available.

**Comment by cinatale** [comment]
Thank you for the tool, very useful indeed! How can I make available the 32bit compiled version? It could be useful for other people, it took quite some time to compile.

**Comment by bcharrow** [comment]
I'm assuming that you compiled version 0.4?  If so, use the release.sh script with version 0.4 and change the linux64 to linux32.  This should be a zip archive.  If you send it to me, I'll test it and add it to the release page.

**Comment by cinatale** [comment]
I hope the attached file is correct… I created it manually since I’m not very usual with Linux scripts…

Best,

C.

Da: Ben Charrow [mailto:notifications@github.com] 
Inviato: martedì 24 giugno 2014 20.42
A: bcharrow/matlab_rosbag
Cc: cinatale
Oggetto: Re: [matlab_rosbag] Compiled versions (#9)

I'm assuming that you compiled version 0.4? If so, use the release.sh script with version 0.4 and change the linux64 to linux32. This should be a zip archive. If you send it to me, I'll test it and add it to the release page.

—
Reply to this email directly or view it on GitHub https://github.com/bcharrow/matlab_rosbag/issues/9#issuecomment-47013174 .

---

Questa e-mail è priva di virus e malware perché è attiva la protezione avast! Antivirus.
http://www.avast.com

**Comment by bcharrow** [comment]
I don't see an attached file.  Can you e-mail it to me directly?  bcharrow@seas.upenn.edu
